backend:
  name: git-gateway
  branch: main

# IMPORTANT: comment this out in production to avoid a blank screen
# local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "text", required: false }
      - { name: "coverImage", label: "Cover Image", widget: "image", required: false }
      - { name: "author", label: "Author", required: false }
      - { name: "body", label: "Body", widget: "markdown" }

local_backend: true